language: python

python:
    - "2.7"

env:
    - DB=mysql

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install build-essential python-dev python-pip python-virtualenv python-imaging mysql-server libmysqlclient-dev libxml2-dev libxslt-dev memcached libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev
    - git submodule update --init --recursive

install:
    - pip install -r requirements/compiled.txt --use-mirrors
    - pip install -r requirements/dev.txt --use-mirrors

script: python manage.py test badger

notifications:
    email:
        recipients:
            - me@lmorchard.com
        on_success: [always|never|change]
        on_failure: [always|never|change]
